development:
  adapter: postgresql
  encoding: unicode
  database: photo_flip_development
  pool: 5
  username: photo_flip
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: photo_flip_test
  pool: 5
  username: photo_flip
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: photo_flip_production
  pool: 5