# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75fbd40d5b488fff1d297b319343f9a3ae61e7faa0ed11c4d8612be6f8e6f86b031cdeeabb40c637446a630db94239b985fd61c6787912d4036aa82d5b63bec4

test:
  secret_key_base: e069c33fbfa7d3619f7d41ab74a2ea6b3f8336ed3eae46c8edcc38371c86f51f74fa43ee2d0d8a79008df24e0740d4304cd5853818cb26d7bc9379263bfc629f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
